# Simulation

In this lesson, we will work through several examples of using random numbers to simulate real-world scenarios.

In [99]:
%matplotlib inline
import numpy as np
import pandas as pd

import viz # curriculum example visualizations

np.random.seed(1349)

### How will we utilize Python to obtain probabilities?

We will utilize Monte Carlo simulations.

A Monte Carlo simulation is a means to recreate potential events and empirically take the results of simiulated trials to obtain a reasonably precise estimate of a desired probability.

What does this mean for us here?

In [79]:
# Let's take a hypothetical base probability. 
# What is the probability of rolling a one (1) on a single, standard, fair six-sided die?

1/6

0.16666666666666666

In [80]:
# Potential outcomes of a die roll:
possible_outcomes = [1,2,3,4,5,6]

In [81]:
# options that equal 1: just 1, literally one

In [82]:
ideal_roll = 1

In [83]:
# Now how would we do this with a simulation?

In [ ]:
# We will do it utilizing a large number of trials, that we calculate.

In [ ]:
# Allow us to examine the same problem: Probability of rolling a 1 on a fair six-sided die.

In [54]:
# First, we will set a value for the number of trials that we want to conduct.
# We have the power of computation at our finger tips, so let's shoot for something like one million.

In [84]:
num_trials = 10 ** 7

In [ ]:
# We have one die roll for each trial, which is our event, that we call a single simulation

In [85]:
n_dice = 1

In [86]:
# We will do a single simulation one million times, with each simulation being a die roll.

In [87]:
rolls = np.random.choice(possible_outcomes, num_trials*n_dice).reshape(num_trials, n_dice)

In [88]:
type(rolls)

numpy.ndarray

In [89]:
# let's make our simulations!

In [90]:
rolls

array([[3],
       [2],
       [5],
       ...,
       [1],
       [2],
       [4]])

In [62]:
rolls.shape

(10000000, 1)

In [63]:
(rolls == 1).mean()

0.1667331

## Generating Random Numbers with Numpy

The `numpy.random` module provides a number of functions for generating random numbers.

- `np.random.choice`: selects random options from a list
- `np.random.uniform`: generates numbers between a given lower and upper bound
- `np.random.random`: generates numbers between 0 and 1
- `np.random.randn`: generates numbers from the standard normal distribution
- `np.random.normal`: generates numbers from a normal distribution with a specified mean and standard deviation

## Example Problems

### Carnival Dice Rolls

> You are at a carnival and come across a person in a booth offering you a game
> of "chance" (as people in booths at carnivals tend to do).

> You pay 5 dollars and roll 3 dice. If the sum of the dice rolls is greater
> than 12, you get 15 dollars. If it's less than or equal to 12, you get
> nothing.

> Assuming the dice are fair, should you play this game? How would this change
> if the winning condition was a sum greater than *or equal to* 12?

To simulate this problem, we'll write the python code to simulate the scenario described above, then repeat it a large amount of times.

One way we can keep track of all the simulations is to use a 2-dimensional matrix. We can create a matrix where each row represents one "trial". Each row will have 3 columns, representing the 3 dice rolls.

In [65]:
n_trials = nrows = 10_000
n_dice = ncols = 3

rolls = np.random.choice([1,2,3,4,5,6], n_trials * n_dice).reshape(nrows, ncols)

In [66]:
rolls

array([[1, 4, 2],
       [1, 2, 3],
       [4, 6, 1],
       ...,
       [3, 6, 2],
       [6, 1, 6],
       [3, 3, 1]])

Here we used the `choice` function to randomly select an element out of the list of the number 1-6, effectively simulating a dice roll. The second argument supplied to `choice` is the total number of dice to roll. Once we have generated all the dice rolls, we use the `.reshape` method to create our matrix with 3 columns and 10,000 rows.

Now that we have all of the simulated dice rolls, we want to get the sum of the dice rolls for each trial. To do this, we can use the `.sum` function and specify that we want the sum of every row (as opposed to the sum of all the numbers, or the sum by column) with the `axis` key word argument.

In [67]:
sums_by_trial = rolls.sum(axis=1)
sums_by_trial

array([ 7,  6, 11, ..., 11, 13,  7])

Let's pause here for a minute and visualize the data we have:

In [101]:
viz.simulation_example1(sums_by_trial)

AttributeError: module 'viz' has no attribute 'simulation_example1'

The area shaded in lightblue represents our chance of winning, that is, the number of times that the sum of 3 dice rolls is greater than 12.

We can now convert each value in our array to a boolean value indicating whether or not we won:

In [94]:
wins = sums_by_trial > 12

To calculate an overall win rate, we can treat each win as a `1` and each loss as `0`, then take the average of the array:

In [72]:
win_rate = wins.mean()

In [73]:
win_rate

0.2585

Now that we know our win rate, we can calculate the expected profit:

In [74]:
expected_winnings = win_rate * 15
cost = 5
expected_profit =  expected_winnings - cost 
expected_profit

-1.1225

So we would expect, based on our simulations, on average, to lose a little over a dollar everytime we play this game.

To answer the last part of the question, we can recalculate our win rate based on the sums being greater than or equal to 12:

In [75]:
wins =  sums_by_trial >= 12
win_rate = wins.mean()
expected_winnings = win_rate * 15
cost = 5
expected_profit = expected_winnings - cost
expected_profit

0.47800000000000065

If our win condition changes to the sum being greater than or equal to 12, then, based on our simulations, on average, we expect to win about 58 cents.

## Mini Exercise:

What is the probability of rolling "snake eyes" on a roll of two (fair) dice?

In [5]:
(1/6) * (1/6)

0.027777777777777776

In [6]:
n_trials = n_rows = 10 ** 6
n_dice = n_cols = 2

### No Rest or Relaxation

> There's a 30% chance my son takes a nap on any given weekend day. What is the chance that he takes a nap at least one day this weekend? What is the probability that he doesn't nap at all?

Let's first do a little bit of setup:

In [7]:
p_nap = 0.3
ndays = n_cols = 2
n_simulated_weekends = n_rows = 10 ** 6

To simulate the results from many weekends, we'll create a 2 x 10,000 matrix, with 2 being the number of days in a weekend and 10,000 being the number of simulations we want to run.

To determine whether or not a nap is taken on a given day, we'll generate a random number between 0 and 1, and say that it is a nap if it is less than our probability of taking a nap.

In [11]:
trials = np.random.random((n_rows, n_cols))

In [12]:
trials[:10]

array([[0.59723552, 0.19408897],
       [0.10592302, 0.94510009],
       [0.18825387, 0.68253688],
       [0.00443933, 0.88240677],
       [0.51053429, 0.45527686],
       [0.68071197, 0.94130535],
       [0.07991815, 0.6600269 ],
       [0.38996208, 0.73630001],
       [0.15183221, 0.94769555],
       [0.93236152, 0.23579507]])

In [13]:
naps = trials < p_nap

In [14]:
naps

array([[False,  True],
       [ True, False],
       [ True, False],
       ...,
       [False, False],
       [False, False],
       [False, False]])

In [15]:
naps.sum(axis=1)

array([1, 1, 1, ..., 0, 0, 0])

Now that we have each day as either true or false, we can take the sum of each row to find the total number of naps for the weekend. When we sum an array of boolean values, numpy will treat `True` as 1 and `False` as 0.

Now we have the results of our simulation, an array where each number in the array represents how many naps were taken in a two day weekend.

In [ ]:
viz.simulation_example2(naps)

We can use this to answer our original questions, what is the probability that at least one nap is taken?

In [17]:
(naps.sum(axis=1) >= 1).mean()

0.510172

What is the probability no naps are taken?

In [19]:
(naps.sum(axis=1) == 0).mean()

0.489828

In [20]:
(naps.sum(axis=1) == 2).mean()

0.090166

## Mini Exercise:

There are ten options in a blind-box style collectable, but you are only likely to get the one you want the most at a probability of one out of every twenty boxes because its a little rarer.

What is the probability of getting your desired collectable if you buy three blindbox toys?

In [21]:
p_win = (1/20)

In [22]:
p_win

0.05

In [23]:
n_trials = n_rows = 10 ** 6
n_simuations = n_cols = 3

In [24]:
total_purchases = np.random.random((n_rows, n_cols))

In [28]:
((total_purchases< p_win).sum(axis=1) >= 1).mean()

0.14261

### One With Dataframes

Let's take a look at one more problem:

> What is the probability of getting at least one 3 in 3 dice rolls?

To simulate this, we'll use a similar strategy to how we modeled the dice rolls in the previous example, but this time, we'll store the results in a pandas dataframe so that we can apply a lambda function that will check to see if one of the rolls was a 3.

In [32]:
n_simulations = nrows = 10 ** 6
n_dice_rolled = ncols = 3

rolls = np.random.choice([1,2,3,4,5,6], n_trials * n_dice_rolled).reshape(n_rows, n_cols)

In [35]:
pd.DataFrame(rolls).apply(lambda row: 3 in row.values, axis=1).mean()

0.421377

Let's break down what's going on here:

1. First we assign values for the number of rows and columns we are going to use
1. Next we create the `rolls` variable that holds a 3 x 10,000 matrix where each element is a randomly chosen number from 1 to 6
1. Lastly we create a dataframe from the rolls
    1. `pd.DataFrame(rolls)` converts our 2d numpy matrix to a pandas DataFrame
    1. `.apply(...` applies a function to each **row** in our dataframe, because we specified `axis=1`, the function will be called with each row as it's argument. The body of the function checks to see if the value `3` is in the values of the row, and will return either `True` or `False`
    1. `.mean()` takes our resulting series of boolean values, and treats `True` as 1 and `False` as 0, to give us the average rate of `True`s, in this case, the simulated probability of getting a 3 in 3 dice rolls.

## Mini Exercise:

Recreate the blindbox problem utilizing the above strategy!


In [43]:
n_rows = 10_000
n_cols = 3
outcomes = [1,2,3,4,5,6,7,8,9,10]
prob_win = 0.05
prob_others = (1-0.05)/9

In [44]:
data = np.random.choice(outcomes, n_rows*n_cols, p = [prob_win, prob_others, prob_others, prob_others, prob_others, prob_others, prob_others, prob_others, prob_others, prob_others]).reshape(n_rows, n_cols)

In [45]:
data[:5]

array([[ 3,  6,  7],
       [10, 10,  9],
       [ 9,  9,  7],
       [ 3,  3,  2],
       [ 9,  6,  7]])

In [46]:
pd.DataFrame(data).apply(lambda row: 1 in row.values, axis=1).mean()

0.1461

## Exercises

Within your `codeup-data-science directory`, create a directory named `statistics-exercises`. This will be where you do your work for this module. Create a repository on GitHub with the same name, and link your local repository to GitHub.

Do your work for this exercise in either a python file named `simulation.py` or a jupyter notebook named `simulation.ipynb`.

In [ ]:
# 1. How likely is it that you roll doubles when rolling two dice?

In [76]:
possible_outcomes = [1,2,3,4,5,6]
num_trials = n_rows = 10 ** 5
n_dice = n_cols = 2

rolls = np.random.choice(possible_outcomes, num_trials, n_dice).reshape(num_trials, n_dice)
rolls

ValueError: cannot reshape array of size 100000 into shape (100000,2)

In [ ]:
# 2. If you flip 8 coins, what is the probability of getting exactly 3 heads? What is the probability of 
# getting more than 3 heads?

In [ ]:
# 3. There are approximitely 3 web development cohorts for every 1 data science cohort at Codeup. 
# Assuming that Codeup randomly selects an alumni to put on a billboard, what are the odds that the 
# two billboards I drive past both have data science students on them?

In [ ]:
# 4. Codeup students buy, on average, 3 poptart packages (+- 1.5) a day from the snack vending machine. 
# If on monday the machine is restocked with 17 poptart packages, how likely is it that I will be able 
# to buy some poptarts on Friday afternoon?

In [ ]:
# 5. Compare Heights
#    - Men have an average height of 178 cm and standard deviation of 8cm.
#    - Women have a mean of 170, sd = 6cm.
#    - If a man and woman are chosen at random, P(woman taller than man)?

In [ ]:
# 6. When installing anaconda on a student's computer, there's a 1 in 250 chance
#    that the download is corrupted and the installation fails. What are the odds
#    that after having 50 students download anaconda, no one has an installation
#    issue?  100 students?

#     What is the probability that we observe an installation issue within the first
#     150 students that download anaconda?

#     How likely is it that 450 students all download anaconda without an issue?

In [ ]:
# 7. There's a 70% chance on any given day that there will be at least one food
#    truck at Travis Park. However, you haven't seen a food truck there in 3 days.
#    How unlikely is this?

#     How likely is it that a food truck will show up sometime this week?

In [ ]:
# 8. If 23 people are in the same room, what are the odds that two of them share a birthday? 
# What if it's 20 people? 40?

#### Bonus Exercises
- [Mage Duel](https://gist.github.com/ryanorsinger/2996446f02c1bf30fcb3f8fdb88bd51d)
- [Chuck a Luck](https://gist.github.com/ryanorsinger/eac1d7b7e978f90b8390bdc056312123)